# Generated by Django 3.2.6 on 2021-09-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='valor',
            field=models.FloatField(),
        ),
    ]
