# Generated by Django 3.2.6 on 2021-09-22 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transferencia_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
